# Módulo bootloader — Calamares
---
efiBootLoader:  "grub"
grubInstall:    "grub-install"
grubMkconfig:   "grub-mkconfig"
grubCfg:        "/boot/grub/grub.cfg"
grubProbe:      "grub-probe"
efiBootloaderId: "HydraOS"

installEFIFallback: true

kernelLine:      "quiet splash"
kernelLineUnrestricted: "quiet splash"

timeout: 5
