# Módulo de paquetes post-instalación — Calamares
---
# Backend de gestión de paquetes
backend: apt

# No instalar recomendados extra durante la instalación para ahorrar tiempo
skip_if_no_internet: false

operations:
  - remove:
      # Eliminar paquetes propios del live que no se necesitan instalados
      - calamares
      - calamares-settings-debian
      - live-boot
      - live-boot-doc
      - live-boot-initramfs-tools
      - live-config
      - live-config-doc
      - live-config-systemd
      - open-vm-tools-desktop
  - install:
      # Paquetes extras que se instalan solo en el sistema final
      - grub-efi-amd64
      - grub-efi-amd64-signed
      - shim-signed
