# Módulo de particionado — Calamares
---
efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: 300
efiSystemPartitionName: "EFI System Partition"

userSwapChoices:
  - none
  - small
  - suspend
  - reuse
  - manual

initialPartitioningChoice: erase
initialSwapChoice: small

drawNestedPartitions:   false
alwaysShowPartitionLabels: true
defaultFileSystemType:  "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs", "f2fs"]

allowManualPartitioning: true
showNotEncryptedBootMessage: true
