# Módulo de usuarios — Calamares
---
defaultGroups:
  - name: sudo
    state: true
  - name: audio
    state: true
  - name: video
    state: true
  - name: input
    state: true
  - name: plugdev
    state: true
  - name: netdev
    state: true
  - name: bluetooth
    state: true
  - name: lpadmin
    state: true
  - name: gamemode
    state: true

autologinGroup:  autologin
doAutologin:     false

setRootPassword: true
doReusePassword: true

passwordRequirements:
  minLength: 6
  maxLength: -1

allowWeakPasswords: false
allowWeakPasswordsDefault: false

userShell: /bin/bash
